---
  name: Deploy Django to Azure
  
  on:
    push:
      branches:
        - main  # Change this if your main branch has a different name
  
  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
  
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.10'  # Change this to match your project’s Python version
  
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
  
        - name: Collect Static Files
          run: python manage.py collectstatic --noinput
  
        - name: Apply Database Migrations
          run: python manage.py migrate
  
        - name: Create Superuser (Optional)
          env:
            DJANGO_SUPERUSER_USERNAME: admin
            DJANGO_SUPERUSER_EMAIL: admin@example.com
            DJANGO_SUPERUSER_PASSWORD: adminpass  # Change this in production!
          run: |
            python manage.py createsuperuser --noinput || true
  
        - name: Deploy to Azure
          uses: azure/webapps-deploy@v2
          with:
            app-name: "statswave-app"  # Your Azure App Service name
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  